Repository kinoticketing/ui, pull requests merged in 2025-01, with the labels that each got.

#52 feat: showtimes are now clickable and lead to detail page
  src/routes/movies/[id]/+page.server.ts
  src/routes/movies/[id]/+page.svelte
  src/routes/movies/[id]/[showtime_id]/+page.svelte
Labels: enhancement

#54 Detail page for halls and showtimes admin
  src/routes/admin/manage-halls/[hall_id]/+page.server.ts
  src/routes/admin/manage-halls/[hall_id]/+page.svelte
  src/routes/admin/manage-screenings/[showtime_id]/+page.server.ts
  src/routes/admin/manage-screenings/[showtime_id]/+page.svelte
Labels: enhancement

#64 feat: improve database and adapt backend logic
  src/routes/admin/manage-halls/+page.server.ts
  src/routes/admin/manage-halls/[hall_id]/+page.server.ts
  src/routes/admin/manage-halls/[hall_id]/+page.svelte
  src/routes/admin/manage-halls/[hall_id]/+server.ts
  src/routes/admin/manage-halls/create-hall/+page.server.ts
  src/routes/admin/manage-screenings/+page.server.ts
  src/routes/admin/manage-screenings/+page.svelte
  src/routes/admin/manage-screenings/[screening_id]/+page.server.ts
  src/routes/admin/manage-screenings/[screening_id]/+page.svelte
  src/routes/admin/manage-screenings/[screening_id]/+server.ts
  src/routes/admin/manage-screenings/[showtime_id]/+page.server.ts
  src/routes/admin/manage-screenings/create-screening/+page.server.ts
  src/routes/admin/manage-screenings/create-screening/+page.svelte
  src/routes/movies/+page.server.ts
  src/routes/movies/[id]/+page.server.ts
  src/routes/movies/[id]/+page.svelte
Labels: enhancement

#71 load movies into db
  src/routes/admin/manage-screenings/create-screening/+page.svelte
  src/routes/admin/manage-screenings/create-screening/save-movie/+server.ts
Labels: enhancement

#76 fix seatplan editor
  src/routes/admin/manage-halls/[hall_id]/+page.server.ts
  src/routes/admin/manage-halls/[hall_id]/+page.svelte
  src/routes/admin/manage-halls/[hall_id]/+server.ts
  src/routes/admin/manage-halls/create-hall/+page.server.ts
  src/routes/admin/manage-halls/create-hall/+page.svelte
  src/routes/admin/manage-screenings/create-screening/+page.server.ts
  src/routes/api/checkout/+server.ts
  src/routes/api/seats/[id]/lock/+server.ts
  src/routes/api/seats/[id]/price/+server.ts
  src/routes/checkout/[payment_id]/$types.ts
  src/routes/checkout/[payment_id]/+page.server.ts
  src/routes/checkout/[payment_id]/+page.svelte
  src/routes/checkout/[payment_id]/types.ts
  src/routes/movies/+page.server.ts
  src/routes/movies/[id]/+page.svelte
  src/routes/movies/[id]/[showtime_id]/+page.server.ts
  src/routes/movies/[id]/[showtime_id]/+page.svelte
  src/routes/movies/[id]/[showtime_id]/types.ts
Labels: enhancement, invalid

#78 feat: payment, tickets, booking page, checkout page, success page
  src/lib/auth.ts
  src/lib/types/paypal.d.ts
  src/routes/api/checkout/+server.ts
  src/routes/api/payments/[payment_id]/paypal/capture/+server.ts
  src/routes/api/payments/[payment_id]/paypal/create/+server.ts
  src/routes/checkout/[payment_id]/+page.server.ts
  src/routes/checkout/[payment_id]/+page.svelte
  src/routes/checkout/[payment_id]/success/+page.server.ts
  src/routes/checkout/[payment_id]/success/+page.svelte
Labels: XL

#90 feat: admin implement manage reservations
  src/routes/admin/manage-halls/+page.svelte
  src/routes/admin/manage-halls/[hall_id]/+page.svelte
  src/routes/admin/manage-halls/create-hall/+page.svelte
  src/routes/admin/manage-reservations/+page.server.ts
  src/routes/admin/manage-reservations/+page.svelte
  src/routes/admin/manage-reservations/[id]/+page.server.ts
  src/routes/admin/manage-reservations/[id]/+page.svelte
  src/routes/admin/manage-screenings/+page.svelte
  src/routes/admin/manage-screenings/[screening_id]/+page.svelte
  src/routes/admin/manage-screenings/create-screening/+page.svelte
Labels: enhancement, feature

#104 feat: revamp admin section
  src/routes/admin/+page.svelte
  src/routes/admin/manage-halls/+page.server.ts
  src/routes/admin/manage-halls/+page.svelte
  src/routes/admin/manage-halls/[hall_id]/+page.svelte
  src/routes/admin/manage-halls/create-hall/+page.svelte
  src/routes/admin/manage-reservations/+page.svelte
  src/routes/admin/manage-screenings/+page.server.ts
  src/routes/admin/manage-screenings/+page.svelte
  src/routes/admin/manage-screenings/[screening_id]/+page.server.ts
  src/routes/admin/manage-screenings/[screening_id]/+page.svelte
  src/routes/admin/manage-screenings/create-screening/+page.svelte
  src/routes/movies/[id]/+page.server.ts
  src/routes/movies/[id]/+page.svelte
Labels: enhancement, feature

#105 feat: footer links
  src/routes/contact/+page.svelte
  src/routes/faq/+page.svelte
  src/routes/privacy/+page.svelte
  src/routes/terms/+page.svelte
Labels: long-term

#124 add edit mode for halls in admin-tool
  src/routes/admin/manage-halls/[hall_id]/+page.server.ts
  src/routes/admin/manage-halls/[hall_id]/+page.svelte
  src/routes/admin/manage-halls/[hall_id]/+server.ts
  src/routes/admin/manage-halls/[hall_id]/admin.manage-halls.[hall_id].server.test.ts
Labels: enhancement

#125 feat: admin edit screenings
  src/routes/admin/manage-screenings/[screening_id]/+page.server.ts
  src/routes/admin/manage-screenings/[screening_id]/+page.svelte
  src/routes/admin/manage-screenings/[screening_id]/+server.ts
  src/routes/admin/manage-screenings/[screening_id]/admin.manage-screenings.[screening_id].server.test.ts
Labels: enhancement, feature
